name: changelog

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      #- name: Install Git
      #  run: 'apt install git'
  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --prune --unshallow  
        
      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
